### ISSUE TITLE
Comic.fx failed to compile in Borderlands 2

### ISSUE THREAD

**Issue by JadeBarker** [Daodan317081/reshade-shaders#5]
When I open my Reshade menu, I get this:
![image](https://user-images.githubusercontent.com/54004034/99728986-7eb1fa00-2a77-11eb-881c-28f593f02136.png)
When I try to activate the shader, I get this:
![image](https://user-images.githubusercontent.com/54004034/99728969-78bc1900-2a77-11eb-912f-160e4dbea5f5.png)

I dislike the default Comic effect the game has because the lines are quite thick, so I disabled them and was hoping to use yours to make them a bit thinner.

**Comment by Daodan317081** [comment]
Sorry to get back to you so late but I fixed it now in [b0e021c](https://github.com/Daodan317081/reshade-shaders/commit/b0e021c4283320c115b1a0220cc65fcafde21dc3). Seems like this was a d3d9 specific problem.
