### ISSUE TITLE
edge upside down

### ISSUE THREAD

**Issue by sovzzz** [Daodan317081/reshade-shaders#6]
the game I'm playing is escape from Tarkov. comic.fx successfully draw the edge of subjects. however the edge is flipped vertically.

**Comment by Daodan317081** [comment]
I haven't used ReShade in a while but there should be a setting in the global preprocessor definitions called DEPTH_BUFFER_IS_UPSIDE_DOWN (or something like that). Enabling that setting should fix the issue.

**Comment by sovzzz** [comment]
> I haven't used ReShade in a while but there should be a setting in the global preprocessor definitions called DEPTH_BUFFER_IS_UPSIDE_DOWN (or something like that). Enabling that setting should fix the issue.

thank you. very helpful!
